## Creating Numpy Arrays

#### 1. array()

In [1]:
import numpy as np

In [2]:
# help(np.array)
# --> array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,like=None)
# --> Create an array.

In [3]:
# 1-D Array using List
L = [10,20,30]
a = np.array(L)
print(L)
print(type(L))
print(a)
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.shape)      # (3,) --> (size of array , )
print(a.size)
# a1 = np.array(L,str)
# print(a1.dtype)

[10, 20, 30]
<class 'list'>
[10 20 30]
<class 'numpy.ndarray'>
1
int64
(3,)
3


In [4]:
# import numpy as np
# help(np.array)
# array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,like=None)

In [5]:
# 2-D Array
L = [[10,20,30],[40,50,60],[70,80,90]]
a = np.array(L)
print(type(a))
print(a.ndim)
print(a)
print(a.shape)
print(a.size)

<class 'numpy.ndarray'>
2
[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
9


In [6]:
# 1-D Array using Tuple
t = ('shubham','kumar','gupta')
a = np.array(t)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)        # <U7 --> string

['shubham' 'kumar' 'gupta']
<class 'numpy.ndarray'>
1
(3,)
3
<U7


In [7]:
# Homo Elements --> upcasting
L = [7,'Dhoni',10,'Sachin',18,'Kohli',45,'Rohit']
a = np.array(L)
print(L)
print(a)
print(a.dtype)
L1 = [10,20,30.5]
a1 = np.array(L1)
print(a1)
print(a1.dtype)

[7, 'Dhoni', 10, 'Sachin', 18, 'Kohli', 45, 'Rohit']
['7' 'Dhoni' '10' 'Sachin' '18' 'Kohli' '45' 'Rohit']
<U21
[10.  20.  30.5]
float64


In [8]:
# How to create an array of a particular type
L1 = [10,20,30.5,0]
a1 = np.array(L1,int)
print(a1)
a2 = np.array(L1,bool)
print(a2)
a3 = np.array(L1,str)
print(a3)
L2 = [7,'Dhoni',10,'Sachin',18,'Kohli',45,'Rohit']
# a = np.array(L2,int)       # ValueError

[10 20 30  0]
[ True  True  True False]
['10' '20' '30.5' '0']


In [9]:
# object type array --> Array with Heterogeneous Elements 
L = [7,'Dhoni',10,'Sachin',18,'Kohli',45,'Rohit',True,10.5,10+20j]
a = np.array(L,object)
print(a)
print(a.dtype)
a1 = np.array(L)
print(a1)
print(a1.dtype)

[7 'Dhoni' 10 'Sachin' 18 'Kohli' 45 'Rohit' True 10.5 (10+20j)]
object
['7' 'Dhoni' '10' 'Sachin' '18' 'Kohli' '45' 'Rohit' 'True' '10.5'
 '(10+20j)']
<U64


#### 2. arange()

In [10]:
# arguments of arange()
# help(np.arange) 
# --> arange([start,] stop[, step,], dtype=None, *, like=None)
# --> Return evenly spaced values within a given interval.

In [11]:
a = np.arange(10)
print(a)
print(a.ndim)
print(a.dtype)

[0 1 2 3 4 5 6 7 8 9]
1
int64


In [12]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
a = np.arange(1,11,2)
a

array([1, 3, 5, 7, 9])

In [14]:
a = np.arange(1,11,3,dtype=float)
a

array([ 1.,  4.,  7., 10.])

In [15]:
# a = np.arange(1,11,3,dtype=str)
# a
# TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

#### 3. linspace()

In [16]:
# in the specified interval , linearly spaced values --> evenly spaced (uniform) numbers
# arguments of linspace()
# help(np.linspace) 
# --> linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)
# --> Return evenly spaced numbers over a specified interval.
# --> Returns `num` evenly spaced samples, calculated over the interval [`start`, `stop`].
# --> The endpoint of the interval can optionally be excluded.

In [17]:
np.linspace(0,1,2)

array([0., 1.])

In [18]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [19]:
np.linspace(0,1,4)

array([0.        , 0.33333333, 0.66666667, 1.        ])

In [20]:
a = np.linspace(0,1)        # dfault argument num=50
print(a)
print('Default Size of array in linspace():',a.size)
print(a.ndim)
print(a.dtype)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]
Default Size of array in linspace(): 50
1
float64


In [21]:
np.linspace(1,100,10,dtype=int)

array([  1,  12,  23,  34,  45,  56,  67,  78,  89, 100])

#### 4. zeros()

In [22]:
# arguments
# help(np.zeros) 
# --> zeros(shape, dtype=float, order='C', *, like=None)
# --> Return a new array of given shape and type, filled with zeros.

In [23]:
# vercor --> 1-D Array
a = np.zeros((10))
print(a)
print('Dimentions:',a.ndim)
print('Shape:',a.shape)
print('Size:',a.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dimentions: 1
Shape: (10,)
Size: 10


In [24]:
# matrix --> 2-D Array --> a collection of 1-D Arrays
a = np.zeros((3,3))
print(a)
print('Dimentions:',a.ndim)
print('Shape:',a.shape)
print('Size:',a.size)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Dimentions: 2
Shape: (3, 3)
Size: 9


In [25]:
# 3-D Array --> a collection of 2-D Arrays
a = np.zeros((2,3,4))
# 2 --> 2 2-D Arrays
# 3 --> No. of rows in every 2-D Array
# 4 --> No. of columns in every 2-D Array
# size = 4*3*2 = 24
print(a)
print('Dimentions:',a.ndim)
print('Shape:',a.shape)
print('Size:',a.size)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Dimentions: 3
Shape: (2, 3, 4)
Size: 24


In [26]:
a = np.zeros((3,3,4))
print(a)
print('Dimentions:',a.ndim)
print('Shape:',a.shape)
print('Size:',a.size)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
Dimentions: 3
Shape: (3, 3, 4)
Size: 36


In [27]:
# dtype argument
a = np.zeros((2,3,4),dtype=int)
print(a)
print('Dimentions:',a.ndim)
print('Shape:',a.shape)
print('Size:',a.size)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
Dimentions: 3
Shape: (2, 3, 4)
Size: 24


In [28]:
a = np.zeros((1,3,2),dtype=int)
print(a)
print('Dimentions:',a.ndim)
print('Shape:',a.shape)
print('Size:',a.size)

[[[0 0]
  [0 0]
  [0 0]]]
Dimentions: 3
Shape: (1, 3, 2)
Size: 6


In [29]:
# 4-D Arrays --> a collection of 3-D Arrays
a = np.zeros((2,2,3,4),dtype=int)
print(a)
print('Dimentions:',a.ndim)
print('Shape:',a.shape)
print('Size:',a.size)

[[[[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]]


 [[[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]

  [[0 0 0 0]
   [0 0 0 0]
   [0 0 0 0]]]]
Dimentions: 4
Shape: (2, 2, 3, 4)
Size: 48


#### 5. ones()

In [30]:
# Exactly similar to zeros() , just the values are 1 instead of 0
# help(np.ones) 
# --> ones(shape, dtype=None, order='C', *, like=None)
# --> Return a new array of given shape and type, filled with ones.

In [31]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

#### 6. full()

In [32]:
# help(np.full)
# --> full(shape, fill_value, dtype=None, order='C', *, like=None)
# --> Return a new array of given shape and type, filled with `fill_value`.

In [33]:
np.full((10),2)

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [34]:
np.full((4,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [35]:
np.full((2,3,4),9)

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

#### 7. eye()

In [3]:
# help(np.eye)
# --> eye(N, M=None, k=0, dtype=<class 'float'>, order='C', *, like=None)
# --> Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [4]:
a = np.eye(2,3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]]


In [5]:
a = np.eye(3,2)
print(a)

[[1. 0.]
 [0. 1.]
 [0. 0.]]


In [7]:
a = np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
a = np.eye(3,dtype=int)
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [11]:
a = np.eye(5,k=1)
print(a)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [15]:
a = np.eye(5,k=-3)
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]]


#### 8. identity()

In [ ]:
# exactly same as eye() function except that 
# 1. It is always square matrix
# 2. only main diagonal contains 1s

In [17]:
# help(np.identity)
# --> identity(n, dtype=None, *, like=None)
# --> Return the identity array.
# --> The identity array is a square array with ones on the main diagonal.

In [18]:
a = np.identity(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
a = np.identity(5,dtype=int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [22]:
# help(np.empty)
# --> empty(shape, dtype=float, order='C', *, like=None)
# --> Return a new array of given shape and type, without initializing entries.

#### 9. empty()

In [23]:
a = np.empty((3,3))
print(a)

[[5.e-324 0.e+000 0.e+000]
 [0.e+000 5.e-324 0.e+000]
 [0.e+000 0.e+000 5.e-324]]


In [24]:
a = np.empty((2,3,4))
print(a)

[[[1.68610835e-316 0.00000000e+000 1.14448379e+243 1.21698002e-152]
  [8.70860497e+183 4.89584248e-085 6.01347002e-154 3.32234062e+257]
  [2.45652619e+198 5.22373805e+257 2.43812981e-152 1.48890307e+195]]

 [[4.96181029e+228 5.98129759e-154 5.66774924e+160 1.28625507e+248]
  [6.01347002e-154 4.47593816e-091 6.01346953e-154 1.95662563e-152]
  [5.98189094e-154 6.01347002e-154 7.03540167e+199 1.54235981e+256]]]


In [26]:
a = np.empty(10)
print(a)

[           35420604                   0                   0
                   0                   0 3472330710117071152
 7076330810053387821 3271411255263179056 4121187706026222642
          1697790257]


In [27]:
a = np.empty(10,dtype=int)
print(a)

[           35420604                   0                   0
                   0                   0 3472330710117071152
 7076330810053387821 3271411255263179056 4121187706026222642
          1697790257]


<!-- zeros() vs. empty() -->

In [29]:
# memory consumption comparision
import sys
a = np.zeros((20000,30,40))
b = np.empty((20000,30,40))
print(sys.getsizeof(a))
print(sys.getsizeof(b))
# no difference

192000144
192000144


#### zeros() vs. empty()
* memory consumption
* time consumption

In [42]:
# Time Consumption Comparision --> empty() is way more faster than zeros()
from datetime import datetime

begin = datetime.now()
a = np.zeros((100000,300,40))
end = datetime.now()
print('Time taken by zeros():',end-begin)
a = None    # making the object eligible for garbage collection
begin = datetime.now()
a = np.empty((100000,300,40))
end = datetime.now()
print('Time taken by empty():',end-begin)

Time taken by zeros(): 0:00:00.000140
Time taken by empty(): 0:00:00.000051
