# Array Manipulation Functions

In [1]:
import numpy as np 

## 1. reshape() 
- **Condition:** Data should not change **==>** input size and output size must match
- **np.reshape()**  : Numpy Library Function
- **array.reshape()** : ndarray class method

#### 1A. 1-D Array

In [22]:
# creating 1-D array 
a = np.random.randint(1,101,10) 
print(a) 
print('Shape:',a.shape)
print('Size:',a.size)
# reshaping 1-D Array to 2-D Array 
b = np.reshape(a,(5,2))
print(b)

[15 58 58 72 30 31  1 72 91 24]
Shape: (10,)
Size: 10
[[15 58]
 [58 72]
 [30 31]
 [ 1 72]
 [91 24]]


In [1]:
# help(np.reshape)

#### 1B. 2-D Array

In [24]:
# creating 1-D Array 
a = np.random.randint(1,101,24)
print(a)
print('Shape:',a.shape)
print('Size:',a.size)
print('Dimentions:',a.ndim)

[ 96  50  66  74  48  27   5  85  31  50   4  37  48  44  39  27  55  42
  62  51   4   7 100  43]
Shape: (24,)
Size: 24
Dimentions: 1


In [25]:
# reshaping 1-D Array to 2-D Array
b = np.reshape(a,(3,8))
print(b)
print('Shape:',b.shape)
print('Size:',b.size)
print('Dimentions:',b.ndim)

[[ 96  50  66  74  48  27   5  85]
 [ 31  50   4  37  48  44  39  27]
 [ 55  42  62  51   4   7 100  43]]
Shape: (3, 8)
Size: 24
Dimentions: 2


In [26]:
# reshaping 2-D Array to 3-D Array
c = np.reshape(b,(2,3,4))
print(c)
print('Shape:',c.shape)
print('Size:',c.size)
print('Dimentions:',c.ndim)

[[[ 96  50  66  74]
  [ 48  27   5  85]
  [ 31  50   4  37]]

 [[ 48  44  39  27]
  [ 55  42  62  51]
  [  4   7 100  43]]]
Shape: (2, 3, 4)
Size: 24
Dimentions: 3


In [28]:
# reshaping 2-D Array to 4-D Array 
e = np.reshape(b,(2,2,2,3))
print(e) 
print('Shape:',e.shape)
print('Size',e.size)
print('Dimentions:',e.ndim)

[[[[ 96  50  66]
   [ 74  48  27]]

  [[  5  85  31]
   [ 50   4  37]]]


 [[[ 48  44  39]
   [ 27  55  42]]

  [[ 62  51   4]
   [  7 100  43]]]]
Shape: (2, 2, 2, 3)
Size 24
Dimentions: 4


In [27]:
# reshaping 2-D Array to 2-D Array of Different Shape 
d = np.reshape(b,(4,6))
print(d)
print('Shape:',d.shape)
print('Size',d.size)
print('Dimentions:',d.ndim)

[[ 96  50  66  74  48  27]
 [  5  85  31  50   4  37]
 [ 48  44  39  27  55  42]
 [ 62  51   4   7 100  43]]
Shape: (4, 6)
Size 24
Dimentions: 2


In [29]:
# reshaping 2-D Array to 2-D Array of Different Shape 
d = np.reshape(b,(6,4))
print(d)
print('Shape:',d.shape)
print('Size',d.size)
print('Dimentions:',d.ndim)

[[ 96  50  66  74]
 [ 48  27   5  85]
 [ 31  50   4  37]
 [ 48  44  39  27]
 [ 55  42  62  51]
 [  4   7 100  43]]
Shape: (6, 4)
Size 24
Dimentions: 2


In [30]:
# reshaping 2-D Array to 2-D Array of Different Shape 
d = np.reshape(b,(8,3))
print(d)
print('Shape:',d.shape)
print('Size',d.size)
print('Dimentions:',d.ndim)

[[ 96  50  66]
 [ 74  48  27]
 [  5  85  31]
 [ 50   4  37]
 [ 48  44  39]
 [ 27  55  42]
 [ 62  51   4]
 [  7 100  43]]
Shape: (8, 3)
Size 24
Dimentions: 2


#### 1C. View of Original only
- ***No New Object is Created***
- ***Change in One is reflected in the other***

In [32]:
a[0] = 7777
print(a)

[7777   50   66   74   48   27    5   85   31   50    4   37   48   44
   39   27   55   42   62   51    4    7  100   43]


In [33]:
print(b)

[[7777   50   66   74   48   27    5   85]
 [  31   50    4   37   48   44   39   27]
 [  55   42   62   51    4    7  100   43]]


In [34]:
print(c)

[[[7777   50   66   74]
  [  48   27    5   85]
  [  31   50    4   37]]

 [[  48   44   39   27]
  [  55   42   62   51]
  [   4    7  100   43]]]


In [35]:
print(d)

[[7777   50   66]
 [  74   48   27]
 [   5   85   31]
 [  50    4   37]
 [  48   44   39]
 [  27   55   42]
 [  62   51    4]
 [   7  100   43]]


In [36]:
print(e)

[[[[7777   50   66]
   [  74   48   27]]

  [[   5   85   31]
   [  50    4   37]]]


 [[[  48   44   39]
   [  27   55   42]]

  [[  62   51    4]
   [   7  100   43]]]]


In [38]:
b[2][0] = 9999
print(b)

[[7777   50   66   74   48   27    5   85]
 [  31   50    4   37   48   44   39   27]
 [9999   42   62   51    4    7  100   43]]


In [39]:
print(a)

[7777   50   66   74   48   27    5   85   31   50    4   37   48   44
   39   27 9999   42   62   51    4    7  100   43]


In [40]:
print(c)

[[[7777   50   66   74]
  [  48   27    5   85]
  [  31   50    4   37]]

 [[  48   44   39   27]
  [9999   42   62   51]
  [   4    7  100   43]]]


In [41]:
print(d)

[[7777   50   66]
 [  74   48   27]
 [   5   85   31]
 [  50    4   37]
 [  48   44   39]
 [  27 9999   42]
 [  62   51    4]
 [   7  100   43]]


In [42]:
print(e)

[[[[7777   50   66]
   [  74   48   27]]

  [[   5   85   31]
   [  50    4   37]]]


 [[[  48   44   39]
   [  27 9999   42]]

  [[  62   51    4]
   [   7  100   43]]]]


#### 1D. Taking Unknown Dimention Size as -1
- ***Value decided by Numpy automatically***
- ***Allowed Only Once***

In [52]:
a = np.random.randint(1,101,12)
print(a)
print('Shape',a.shape)

[18 32 69 13 18 97  9 22  1 48 19 83]
Shape (12,)


In [53]:
b = np.reshape(a,(6,-1))
print(b)
print('Shape',b.shape)

[[18 32]
 [69 13]
 [18 97]
 [ 9 22]
 [ 1 48]
 [19 83]]
Shape (12,)


In [54]:
b = np.reshape(a,(3,-1))
print(b)
print('Shape',b.shape)

[[18 32 69 13]
 [18 97  9 22]
 [ 1 48 19 83]]
Shape (3, 4)


In [55]:
b = np.reshape(a,(-1,6))
print(b)
print('Shape',b.shape)

[[18 32 69 13 18 97]
 [ 9 22  1 48 19 83]]
Shape (2, 6)


In [56]:
b = np.reshape(a,(-1,3))
print(b)
print('Shape',b.shape)

[[18 32 69]
 [13 18 97]
 [ 9 22  1]
 [48 19 83]]
Shape (4, 3)


In [58]:
c = np.reshape(a,(2,3,-1))
print(c)
print('Shape',c.shape)

[[[18 32]
  [69 13]
  [18 97]]

 [[ 9 22]
  [ 1 48]
  [19 83]]]
Shape (2, 3, 2)


In [59]:
c = np.reshape(a,(2,-1,3))
print(c)
print('Shape',c.shape)

[[[18 32 69]
  [13 18 97]]

 [[ 9 22  1]
  [48 19 83]]]
Shape (2, 2, 3)


In [61]:
c = np.reshape(a,(-1,2,2))
print(c)
print('Shape',c.shape)

[[[18 32]
  [69 13]]

 [[18 97]
  [ 9 22]]

 [[ 1 48]
  [19 83]]]
Shape (3, 2, 2)


#### 1E. ValueError : Different Cases

In [57]:
# b = np.reshape(a,(-1,-1))
# ValueError: can only specify one unknown dimension

In [63]:
# c = np.reshape(a,(5,-1))
# ValueError: cannot reshape array of size 12 into shape (5,newaxis)

#### 1F. order Argument (Optional)
- order='C' (Default): C Style : Row Major Order
- order='F' : Fortran Styly : Column Manor Order
- order='A' : Fortran Styly 

In [78]:
# Example 1 
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [80]:
# order='C'
b = np.reshape(a,(12,),'C')
print(b)
b = np.reshape(a,(12,))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [81]:
# order='F'
c = np.reshape(a,(12,),'F')
print(c)

[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [75]:
# Example 2
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [76]:
b = np.reshape(a,(6,4))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [77]:
c = np.reshape(a,(6,4),'F')
print(c)

[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


## 2. resize()
- Input Size and Output Size need not match
- The Data may change
- We will get **Copy** , not view
- **np.resize()** : repeats elements of input array
- **array.resize()** : uses **zero** for **extra elements**, **Inline Modification**
- Taking Unknown Dimention Size as -1 is **not applicable**

In [100]:
# help(np.resize) 

In [83]:
a = np.arange(1,6)
print(a)

[1 2 3 4 5]


In [85]:
b = np.resize(a,(2,3))
print(b)

[[1 2 3]
 [4 5 1]]


#### 2A. np.resize()
**repeats elements of input array**

In [86]:
b = np.resize(a,(4,3))
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]]


#### 2B. Copy but not View
- **change in one does not affect the other**

In [89]:
a[0] = 7777
print(a)

[7777    2    3    4    5]


In [90]:
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]]


#### 2C. Taking Unknown Dimention Size as -1 
***not applicable***

In [93]:
# b = np.resize(a,(5,-1))
# ValueError: all elements of `new_shape` must be non-negative

#### 2D. ndarray.resize()
- uses **zero** for extra elements
- **Inline Modification**

In [94]:
b = a.resize(5,3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [98]:
a = np.arange(1,6)
print(a)
b = a.resize(5,3)
print(a)
# inline modification check 
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
None


#### 2E. numpy.resize() vs. ndarray.resize()

In [2]:
# numpy.resize() --> returns new ndarray 
a = np.random.randint(1,101,(3,4))
print(a)

[[90 69 10 27]
 [63 60 77 55]
 [53 95 60 60]]


In [4]:
b = np.resize(a,(2,3,4)) 
print(b)

[[[90 69 10 27]
  [63 60 77 55]
  [53 95 60 60]]

 [[90 69 10 27]
  [63 60 77 55]
  [53 95 60 60]]]


In [10]:
# ndarray.resize() --> inline modification 
a = np.random.randint(1,101,(3,4))
print(a)
b = a.resize(2,3,4) 
print(b)

[[51 49 68 14]
 [97 42 97 68]
 [45 28 86 98]]
None


In [11]:
print(a) 

[[[51 49 68 14]
  [97 42 97 68]
  [45 28 86 98]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]]


## resize() vs. reshape()
***VVI for Interviews***

***refer class notes***

***LinkedIn Post :***
  https://www.linkedin.com/feed/update/urn:li:activity:7176761178570858498/

## 3. flatten() 

#### -> method of ndarray class and not a function of numpy library

In [25]:
# 2-D -> 1-D
a = np.random.randint(1,101,(2,5))
print(a)

[[ 8 35 76  8 37]
 [72 81 58 48 53]]


In [26]:
# b = np.flatten(a) 
# AttributeError: module 'numpy' has no attribute 'flatten' 

In [27]:
# help(np.ndarray.flatten) 
'''
flatten(...)
    a.flatten(order='C')
    
    Return a copy of the array collapsed into one dimension.
'''

"\nflatten(...)\n    a.flatten(order='C')\n    \n    Return a copy of the array collapsed into one dimension.\n"

In [28]:
a = np.random.randint(1,101,(2,5))
print(a)

[[33 75 66 71 92]
 [33 73  7 92 59]]


In [29]:
b = a.flatten()
print(b)

[33 75 66 71 92 33 73  7 92 59]


In [43]:
a = np.random.randint(1,101,(2,3,4))
print(a)

[[[88 43 23 82]
  [32 46 60 73]
  [94 18 90  4]]

 [[28 69 20 42]
  [48 22 28 16]
  [54 57  5 29]]]


In [44]:
b = a.flatten()
print(b)

[88 43 23 82 32 46 60 73 94 18 90  4 28 69 20 42 48 22 28 16 54 57  5 29]


In [45]:
c = a.flatten(order='F')
print(c)

[88 28 32 48 94 54 43 69 46 22 18 57 23 20 60 28 90  5 82 42 73 16  4 29]


#### -> separate copy but not view

In [46]:
a[0][0][0] = 7777
print(a)

[[[7777   43   23   82]
  [  32   46   60   73]
  [  94   18   90    4]]

 [[  28   69   20   42]
  [  48   22   28   16]
  [  54   57    5   29]]]


In [47]:
print(b)

[88 43 23 82 32 46 60 73 94 18 90  4 28 69 20 42 48 22 28 16 54 57  5 29]


In [48]:
print(c)

[88 28 32 48 94 54 43 69 46 22 18 57 23 20 60 28 90  5 82 42 73 16  4 29]


#### -> order

In [52]:
a = np.arange(1,19).reshape(3,3,2)
print('Dimentions:',a.ndim)
print(a)

Reshape: 3
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [53]:
b = a.flatten()
print('Dimentions:',b.ndim)
print(b)

Dimentions: 1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


#### -> flat variable

In [2]:
a = np.random.randint(1,101,(2,3,4))
print(a)

[[[69 69 31 76]
  [40 55 21 85]
  [ 4 29  6 67]]

 [[75 84 48  7]
  [ 6 17 73 74]
  [12 88 73 35]]]


In [3]:
a.flat

In [4]:
a.flat[2]

31

In [6]:
a.flat[10]

6

In [10]:
for x in a.flat:print(x,end=' ')

69 69 31 76 40 55 21 85 4 29 6 67 75 84 48 7 6 17 73 74 12 88 73 35 

In [11]:
# help(np.flatiter) 
'''
Help on class flatiter in module numpy:

class flatiter(builtins.object)
 |  Flat iterator object to iterate over arrays.
'''

'\nHelp on class flatiter in module numpy:\n\nclass flatiter(builtins.object)\n |  Flat iterator object to iterate over arrays.\n'

## 4. ravel()

In [15]:
# help(np.ravel) 
'''
Help on _ArrayFunctionDispatcher in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
'''

"\nHelp on _ArrayFunctionDispatcher in module numpy:\n\nravel(a, order='C')\n    Return a contiguous flattened array.\n"

In [13]:
a = np.random.randint(1,101,(3,2,3))
print(a)

[[[99 86 16]
  [ 2 28 92]]

 [[64 21 81]
  [50 83 51]]

 [[ 2 82  6]
  [29 21 37]]]


#### -> ndarray class method

In [16]:
b = a.ravel()
print(b)

[99 86 16  2 28 92 64 21 81 50 83 51  2 82  6 29 21 37]


#### -> numpy library function

In [18]:
c = np.ravel(a)
print(c)

[99 86 16  2 28 92 64 21 81 50 83 51  2 82  6 29 21 37]


#### returns view but not copy 

In [19]:
b[0] = 7777
print(b)

[7777   86   16    2   28   92   64   21   81   50   83   51    2   82
    6   29   21   37]


In [20]:
print(c)

[7777   86   16    2   28   92   64   21   81   50   83   51    2   82
    6   29   21   37]


In [21]:
print(a)

[[[7777   86   16]
  [   2   28   92]]

 [[  64   21   81]
  [  50   83   51]]

 [[   2   82    6]
  [  29   21   37]]]


## 5. transpose()

In [28]:
# help(np.transpose) 
'''
transpose(a, axes=None)
    Returns an array with axes transposed.
'''

'\ntranspose(a, axes=None)\n    Returns an array with axes transposed.\n'

#### -> interchanges rows and columns

In [26]:
a = np.random.randint(1,101,(3,4))
print(a)
print('dimentions:',a.ndim)
print('shape:',a.shape)

[[90 73 65 82]
 [69 82 66  4]
 [65 64 32 86]]
dimentions: 2
shape: (3, 4)


In [27]:
b = np.transpose(a)
print(b)
print('dimentions:',b.ndim)
print('shape:',b.shape)

[[90 69 65]
 [73 82 64]
 [65 66 32]
 [82  4 86]]
dimentions: 2
shape: (4, 3)


#### -> returns view but not copy

In [29]:
b[0][0] = 7777
print(b)

[[7777   69   65]
 [  73   82   64]
 [  65   66   32]
 [  82    4   86]]


In [30]:
print(a)

[[7777   73   65   82]
 [  69   82   66    4]
 [  65   64   32   86]]
