# Array Manipulation Functions

In [2]:
import numpy as np 

## 1. reshape() 
- **Condition:** Data should not change **==>** input size and output size must match
- **np.reshape()**  : Numpy Library Function
- **array.reshape()** : ndarray class method

#### 1A. 1-D Array

In [22]:
# creating 1-D array 
a = np.random.randint(1,101,10) 
print(a) 
print('Shape:',a.shape)
print('Size:',a.size)
# reshaping 1-D Array to 2-D Array 
b = np.reshape(a,(5,2))
print(b)

[15 58 58 72 30 31  1 72 91 24]
Shape: (10,)
Size: 10
[[15 58]
 [58 72]
 [30 31]
 [ 1 72]
 [91 24]]


In [1]:
# help(np.reshape)

#### 1B. 2-D Array

In [24]:
# creating 1-D Array 
a = np.random.randint(1,101,24)
print(a)
print('Shape:',a.shape)
print('Size:',a.size)
print('Dimentions:',a.ndim)

[ 96  50  66  74  48  27   5  85  31  50   4  37  48  44  39  27  55  42
  62  51   4   7 100  43]
Shape: (24,)
Size: 24
Dimentions: 1


In [25]:
# reshaping 1-D Array to 2-D Array
b = np.reshape(a,(3,8))
print(b)
print('Shape:',b.shape)
print('Size:',b.size)
print('Dimentions:',b.ndim)

[[ 96  50  66  74  48  27   5  85]
 [ 31  50   4  37  48  44  39  27]
 [ 55  42  62  51   4   7 100  43]]
Shape: (3, 8)
Size: 24
Dimentions: 2


In [26]:
# reshaping 2-D Array to 3-D Array
c = np.reshape(b,(2,3,4))
print(c)
print('Shape:',c.shape)
print('Size:',c.size)
print('Dimentions:',c.ndim)

[[[ 96  50  66  74]
  [ 48  27   5  85]
  [ 31  50   4  37]]

 [[ 48  44  39  27]
  [ 55  42  62  51]
  [  4   7 100  43]]]
Shape: (2, 3, 4)
Size: 24
Dimentions: 3


In [28]:
# reshaping 2-D Array to 4-D Array 
e = np.reshape(b,(2,2,2,3))
print(e) 
print('Shape:',e.shape)
print('Size',e.size)
print('Dimentions:',e.ndim)

[[[[ 96  50  66]
   [ 74  48  27]]

  [[  5  85  31]
   [ 50   4  37]]]


 [[[ 48  44  39]
   [ 27  55  42]]

  [[ 62  51   4]
   [  7 100  43]]]]
Shape: (2, 2, 2, 3)
Size 24
Dimentions: 4


In [27]:
# reshaping 2-D Array to 2-D Array of Different Shape 
d = np.reshape(b,(4,6))
print(d)
print('Shape:',d.shape)
print('Size',d.size)
print('Dimentions:',d.ndim)

[[ 96  50  66  74  48  27]
 [  5  85  31  50   4  37]
 [ 48  44  39  27  55  42]
 [ 62  51   4   7 100  43]]
Shape: (4, 6)
Size 24
Dimentions: 2


In [29]:
# reshaping 2-D Array to 2-D Array of Different Shape 
d = np.reshape(b,(6,4))
print(d)
print('Shape:',d.shape)
print('Size',d.size)
print('Dimentions:',d.ndim)

[[ 96  50  66  74]
 [ 48  27   5  85]
 [ 31  50   4  37]
 [ 48  44  39  27]
 [ 55  42  62  51]
 [  4   7 100  43]]
Shape: (6, 4)
Size 24
Dimentions: 2


In [30]:
# reshaping 2-D Array to 2-D Array of Different Shape 
d = np.reshape(b,(8,3))
print(d)
print('Shape:',d.shape)
print('Size',d.size)
print('Dimentions:',d.ndim)

[[ 96  50  66]
 [ 74  48  27]
 [  5  85  31]
 [ 50   4  37]
 [ 48  44  39]
 [ 27  55  42]
 [ 62  51   4]
 [  7 100  43]]
Shape: (8, 3)
Size 24
Dimentions: 2


#### 1C. View of Original only
- ***No New Object is Created***
- ***Change in One is reflected in the other***

In [32]:
a[0] = 7777
print(a)

[7777   50   66   74   48   27    5   85   31   50    4   37   48   44
   39   27   55   42   62   51    4    7  100   43]


In [33]:
print(b)

[[7777   50   66   74   48   27    5   85]
 [  31   50    4   37   48   44   39   27]
 [  55   42   62   51    4    7  100   43]]


In [34]:
print(c)

[[[7777   50   66   74]
  [  48   27    5   85]
  [  31   50    4   37]]

 [[  48   44   39   27]
  [  55   42   62   51]
  [   4    7  100   43]]]


In [35]:
print(d)

[[7777   50   66]
 [  74   48   27]
 [   5   85   31]
 [  50    4   37]
 [  48   44   39]
 [  27   55   42]
 [  62   51    4]
 [   7  100   43]]


In [36]:
print(e)

[[[[7777   50   66]
   [  74   48   27]]

  [[   5   85   31]
   [  50    4   37]]]


 [[[  48   44   39]
   [  27   55   42]]

  [[  62   51    4]
   [   7  100   43]]]]


In [38]:
b[2][0] = 9999
print(b)

[[7777   50   66   74   48   27    5   85]
 [  31   50    4   37   48   44   39   27]
 [9999   42   62   51    4    7  100   43]]


In [39]:
print(a)

[7777   50   66   74   48   27    5   85   31   50    4   37   48   44
   39   27 9999   42   62   51    4    7  100   43]


In [40]:
print(c)

[[[7777   50   66   74]
  [  48   27    5   85]
  [  31   50    4   37]]

 [[  48   44   39   27]
  [9999   42   62   51]
  [   4    7  100   43]]]


In [41]:
print(d)

[[7777   50   66]
 [  74   48   27]
 [   5   85   31]
 [  50    4   37]
 [  48   44   39]
 [  27 9999   42]
 [  62   51    4]
 [   7  100   43]]


In [42]:
print(e)

[[[[7777   50   66]
   [  74   48   27]]

  [[   5   85   31]
   [  50    4   37]]]


 [[[  48   44   39]
   [  27 9999   42]]

  [[  62   51    4]
   [   7  100   43]]]]


#### 1D. Taking Unknown Dimention Size as -1
- ***Value decided by Numpy automatically***
- ***Allowed Only Once***

In [52]:
a = np.random.randint(1,101,12)
print(a)
print('Shape',a.shape)

[18 32 69 13 18 97  9 22  1 48 19 83]
Shape (12,)


In [53]:
b = np.reshape(a,(6,-1))
print(b)
print('Shape',b.shape)

[[18 32]
 [69 13]
 [18 97]
 [ 9 22]
 [ 1 48]
 [19 83]]
Shape (12,)


In [54]:
b = np.reshape(a,(3,-1))
print(b)
print('Shape',b.shape)

[[18 32 69 13]
 [18 97  9 22]
 [ 1 48 19 83]]
Shape (3, 4)


In [55]:
b = np.reshape(a,(-1,6))
print(b)
print('Shape',b.shape)

[[18 32 69 13 18 97]
 [ 9 22  1 48 19 83]]
Shape (2, 6)


In [56]:
b = np.reshape(a,(-1,3))
print(b)
print('Shape',b.shape)

[[18 32 69]
 [13 18 97]
 [ 9 22  1]
 [48 19 83]]
Shape (4, 3)


In [58]:
c = np.reshape(a,(2,3,-1))
print(c)
print('Shape',c.shape)

[[[18 32]
  [69 13]
  [18 97]]

 [[ 9 22]
  [ 1 48]
  [19 83]]]
Shape (2, 3, 2)


In [59]:
c = np.reshape(a,(2,-1,3))
print(c)
print('Shape',c.shape)

[[[18 32 69]
  [13 18 97]]

 [[ 9 22  1]
  [48 19 83]]]
Shape (2, 2, 3)


In [61]:
c = np.reshape(a,(-1,2,2))
print(c)
print('Shape',c.shape)

[[[18 32]
  [69 13]]

 [[18 97]
  [ 9 22]]

 [[ 1 48]
  [19 83]]]
Shape (3, 2, 2)


#### 1E. ValueError : Different Cases

In [57]:
# b = np.reshape(a,(-1,-1))
# ValueError: can only specify one unknown dimension

In [63]:
# c = np.reshape(a,(5,-1))
# ValueError: cannot reshape array of size 12 into shape (5,newaxis)

#### 1F. order Argument (Optional)
- order='C' (Default): C Style : Row Major Order
- order='F' : Fortran Styly : Column Manor Order
- order='A' : Fortran Styly 

In [78]:
# Example 1 
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [80]:
# order='C'
b = np.reshape(a,(12,),'C')
print(b)
b = np.reshape(a,(12,))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [81]:
# order='F'
c = np.reshape(a,(12,),'F')
print(c)

[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [75]:
# Example 2
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [76]:
b = np.reshape(a,(6,4))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [77]:
c = np.reshape(a,(6,4),'F')
print(c)

[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


## 2. resize()
- Input Size and Output Size need not match
- The Data may change
- We will get **Copy** , not view
- **np.resize()** : repeats elements of input array
- **array.resize()** : uses **zero** for **extra elements**, **Inline Modification**
- Taking Unknown Dimention Size as -1 is **not applicable**

In [100]:
# help(np.resize) 

In [83]:
a = np.arange(1,6)
print(a)

[1 2 3 4 5]


In [85]:
b = np.resize(a,(2,3))
print(b)

[[1 2 3]
 [4 5 1]]


#### 2A. np.resize()
**repeats elements of input array**

In [86]:
b = np.resize(a,(4,3))
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]]


#### 2B. Copy but not View
- **change in one does not affect the other**

In [89]:
a[0] = 7777
print(a)

[7777    2    3    4    5]


In [90]:
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]]


#### 2C. Taking Unknown Dimention Size as -1 
***not applicable***

In [93]:
# b = np.resize(a,(5,-1))
# ValueError: all elements of `new_shape` must be non-negative

#### 2D. ndarray.resize()
- uses **zero** for extra elements
- **Inline Modification**

In [94]:
b = a.resize(5,3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [98]:
a = np.arange(1,6)
print(a)
b = a.resize(5,3)
print(a)
# inline modification check 
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
None


#### 2E. numpy.resize() vs. ndarray.resize()

In [2]:
# numpy.resize() --> returns new ndarray 
a = np.random.randint(1,101,(3,4))
print(a)

[[90 69 10 27]
 [63 60 77 55]
 [53 95 60 60]]


In [4]:
b = np.resize(a,(2,3,4)) 
print(b)

[[[90 69 10 27]
  [63 60 77 55]
  [53 95 60 60]]

 [[90 69 10 27]
  [63 60 77 55]
  [53 95 60 60]]]


In [10]:
# ndarray.resize() --> inline modification 
a = np.random.randint(1,101,(3,4))
print(a)
b = a.resize(2,3,4) 
print(b)

[[51 49 68 14]
 [97 42 97 68]
 [45 28 86 98]]
None


In [11]:
print(a) 

[[[51 49 68 14]
  [97 42 97 68]
  [45 28 86 98]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]]


## reshape() vs. resize()
***VVI for Interviews***

***refer class notes***

***LinkedIn Post :***
  https://www.linkedin.com/feed/update/urn:li:activity:7176761178570858498/

## 3. flatten() 

#### -> method of ndarray class and not a function of numpy library

In [25]:
# 2-D -> 1-D
a = np.random.randint(1,101,(2,5))
print(a)

[[ 8 35 76  8 37]
 [72 81 58 48 53]]


In [26]:
# b = np.flatten(a) 
# AttributeError: module 'numpy' has no attribute 'flatten' 

In [27]:
# help(np.ndarray.flatten) 
'''
flatten(...)
    a.flatten(order='C')
    
    Return a copy of the array collapsed into one dimension.
'''

"\nflatten(...)\n    a.flatten(order='C')\n    \n    Return a copy of the array collapsed into one dimension.\n"

In [28]:
a = np.random.randint(1,101,(2,5))
print(a)

[[33 75 66 71 92]
 [33 73  7 92 59]]


In [29]:
b = a.flatten()
print(b)

[33 75 66 71 92 33 73  7 92 59]


In [43]:
a = np.random.randint(1,101,(2,3,4))
print(a)

[[[88 43 23 82]
  [32 46 60 73]
  [94 18 90  4]]

 [[28 69 20 42]
  [48 22 28 16]
  [54 57  5 29]]]


In [44]:
b = a.flatten()
print(b)

[88 43 23 82 32 46 60 73 94 18 90  4 28 69 20 42 48 22 28 16 54 57  5 29]


In [45]:
c = a.flatten(order='F')
print(c)

[88 28 32 48 94 54 43 69 46 22 18 57 23 20 60 28 90  5 82 42 73 16  4 29]


#### -> separate copy but not view

In [46]:
a[0][0][0] = 7777
print(a)

[[[7777   43   23   82]
  [  32   46   60   73]
  [  94   18   90    4]]

 [[  28   69   20   42]
  [  48   22   28   16]
  [  54   57    5   29]]]


In [47]:
print(b)

[88 43 23 82 32 46 60 73 94 18 90  4 28 69 20 42 48 22 28 16 54 57  5 29]


In [48]:
print(c)

[88 28 32 48 94 54 43 69 46 22 18 57 23 20 60 28 90  5 82 42 73 16  4 29]


#### -> order

In [52]:
a = np.arange(1,19).reshape(3,3,2)
print('Dimentions:',a.ndim)
print(a)

Reshape: 3
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]


In [53]:
b = a.flatten()
print('Dimentions:',b.ndim)
print(b)

Dimentions: 1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


#### -> flat variable

In [2]:
a = np.random.randint(1,101,(2,3,4))
print(a)

[[[69 69 31 76]
  [40 55 21 85]
  [ 4 29  6 67]]

 [[75 84 48  7]
  [ 6 17 73 74]
  [12 88 73 35]]]


In [3]:
a.flat

In [4]:
a.flat[2]

31

In [6]:
a.flat[10]

6

In [10]:
for x in a.flat:print(x,end=' ')

69 69 31 76 40 55 21 85 4 29 6 67 75 84 48 7 6 17 73 74 12 88 73 35 

In [11]:
# help(np.flatiter) 
'''
Help on class flatiter in module numpy:

class flatiter(builtins.object)
 |  Flat iterator object to iterate over arrays.
'''

'\nHelp on class flatiter in module numpy:\n\nclass flatiter(builtins.object)\n |  Flat iterator object to iterate over arrays.\n'

## 4. ravel()

In [15]:
# help(np.ravel) 
'''
Help on _ArrayFunctionDispatcher in module numpy:

ravel(a, order='C')
    Return a contiguous flattened array.
'''

"\nHelp on _ArrayFunctionDispatcher in module numpy:\n\nravel(a, order='C')\n    Return a contiguous flattened array.\n"

In [13]:
a = np.random.randint(1,101,(3,2,3))
print(a)

[[[99 86 16]
  [ 2 28 92]]

 [[64 21 81]
  [50 83 51]]

 [[ 2 82  6]
  [29 21 37]]]


#### -> ndarray class method

In [16]:
b = a.ravel()
print(b)

[99 86 16  2 28 92 64 21 81 50 83 51  2 82  6 29 21 37]


#### -> numpy library function

In [18]:
c = np.ravel(a)
print(c)

[99 86 16  2 28 92 64 21 81 50 83 51  2 82  6 29 21 37]


#### returns view but not copy 

In [19]:
b[0] = 7777
print(b)

[7777   86   16    2   28   92   64   21   81   50   83   51    2   82
    6   29   21   37]


In [20]:
print(c)

[7777   86   16    2   28   92   64   21   81   50   83   51    2   82
    6   29   21   37]


In [21]:
print(a)

[[[7777   86   16]
  [   2   28   92]]

 [[  64   21   81]
  [  50   83   51]]

 [[   2   82    6]
  [  29   21   37]]]


## 5. transpose()
- not usefull for 1-D arrays

### numpy.transpose() -> numpy library function

In [28]:
# help(np.transpose) 
'''
transpose(a, axes=None)
    Returns an array with axes transposed.
'''

'\ntranspose(a, axes=None)\n    Returns an array with axes transposed.\n'

#### -> 2-D ndarray

#### -> interchanges rows and columns

In [26]:
a = np.random.randint(1,101,(3,4))
print(a)
print('dimentions:',a.ndim)
print('shape:',a.shape)

[[90 73 65 82]
 [69 82 66  4]
 [65 64 32 86]]
dimentions: 2
shape: (3, 4)


In [27]:
b = np.transpose(a)
print(b)
print('dimentions:',b.ndim)
print('shape:',b.shape)

[[90 69 65]
 [73 82 64]
 [65 66 32]
 [82  4 86]]
dimentions: 2
shape: (4, 3)


#### -> returns view but not copy

In [29]:
b[0][0] = 7777
print(b)

[[7777   69   65]
 [  73   82   64]
 [  65   66   32]
 [  82    4   86]]


In [30]:
print(a)

[[7777   73   65   82]
 [  69   82   66    4]
 [  65   64   32   86]]


#### -> 3-D ndarray

In [6]:
a = np.random.randint(1,101,(2,3,4))
print(a)
print('dimentions:',a.ndim)
print('shape:',a.shape)
print('size:',a.size)

[[[60 46 83 27]
  [ 3 96 38 58]
  [39 65 52 24]]

 [[21  7 19 59]
  [77 84 40 33]
  [59 41 30 95]]]
dimentions: 3
shape: (2, 3, 4)
size: 24


In [7]:
b = np.transpose(a)
print(b)
print('dimentions:',b.ndim)
print('shape:',b.shape)
print('size:',b.size)

[[[60 21]
  [ 3 77]
  [39 59]]

 [[46  7]
  [96 84]
  [65 41]]

 [[83 19]
  [38 40]
  [52 30]]

 [[27 59]
  [58 33]
  [24 95]]]
dimentions: 3
shape: (4, 3, 2)
size: 24


#### -> axes parameter
- not usefull for 2-D arrays

In [12]:
a = np.random.randint(1,101,(2,3,4))
print(a)
print('dimentions:',a.ndim)
print('shape:',a.shape)
print('size:',a.size)

[[[53 40 55 82]
  [70  3 92 47]
  [ 9 74 47 71]]

 [[28 35 81 90]
  [51 31 98 69]
  [80 34 16  4]]]
dimentions: 3
shape: (2, 3, 4)
size: 24


In [16]:
b = np.transpose(a,axes=(0,2,1))
print(b)
print('dimentions:',b.ndim)
print('shape:',b.shape)
print('size:',b.size)

[[[53 70  9]
  [40  3 74]
  [55 92 47]
  [82 47 71]]

 [[28 51 80]
  [35 31 34]
  [81 98 16]
  [90 69  4]]]
dimentions: 3
shape: (2, 4, 3)
size: 24


In [17]:
c = np.transpose(a,axes=(1,2,0))
print(c)
print('dimentions:',c.ndim)
print('shape:',c.shape)
print('size:',c.size)

[[[53 28]
  [40 35]
  [55 81]
  [82 90]]

 [[70 51]
  [ 3 31]
  [92 98]
  [47 69]]

 [[ 9 80]
  [74 34]
  [47 16]
  [71  4]]]
dimentions: 3
shape: (3, 4, 2)
size: 24


In [19]:
d = np.transpose(a,axes=(2,0,1))
print(d)
print('dimentions:',d.ndim)
print('shape:',d.shape)
print('size:',d.size)

[[[53 70  9]
  [28 51 80]]

 [[40  3 74]
  [35 31 34]]

 [[55 92 47]
  [81 98 16]]

 [[82 47 71]
  [90 69  4]]]
dimentions: 3
shape: (4, 2, 3)
size: 24


#### -> ValueError: repeated axis in transpose

In [20]:
e = np.transpose(a,axes=(0,2,2))

ValueError: repeated axis in transpose

### ndarray.transpose() -> ndarray class method

#### -> same as numpy.transpose()

In [22]:
# help(np.ndarray.transpose)
'''
transpose(...)
    a.transpose(*axes)
    
    Returns a view of the array with axes transposed.
    
    Refer to `numpy.transpose` for full documentation.
'''

'\ntranspose(...)\n    a.transpose(*axes)\n    \n    Returns a view of the array with axes transposed.\n    \n    Refer to `numpy.transpose` for full documentation.\n'

In [31]:
a = np.arange(24).reshape(2,3,4)
print(a)
print('dimentions:',a.ndim)
print('shape:',a.shape)
print('size:',a.size)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
dimentions: 3
shape: (2, 3, 4)
size: 24


In [32]:
b = a.transpose()
print(b)
print('dimentions:',b.ndim)
print('shape:',b.shape)
print('size:',b.size)

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
dimentions: 3
shape: (4, 3, 2)
size: 24


In [34]:
c = a.transpose(2,0,1)
print(c)
print('dimentions:',c.ndim)
print('shape:',c.shape)
print('size:',c.size)

[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]
dimentions: 3
shape: (4, 2, 3)
size: 24


#### -> shortcut representation of transpose 

In [35]:
e = a.T
print(e)
print('dimentions:',e.ndim)
print('shape:',e.shape)
print('size:',e.size)

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
dimentions: 3
shape: (4, 3, 2)
size: 24


## 6. swapaxes()
- swap only two axes but not all

In [37]:
# help(np.swapaxes) 
''' 
swapaxes(a, axis1, axis2)
    Interchange two axes of an array.
'''

' \nswapaxes(a, axis1, axis2)\n    Interchange two axes of an array.\n'

### numpy.swapaxes()
- numpy library function

In [40]:
a = np.arange(24).reshape(2,3,4)
print(a) 
print('dimentions:',a.ndim)
print('shape:',a.shape)
print('size:',a.size)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
dimentions: 3
shape: (2, 3, 4)
size: 24


In [42]:
b = np.swapaxes(a,1,2)
print(b)
print('dimentions:',b.ndim)
print('shape:',b.shape)
print('size:',b.size)

[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
dimentions: 3
shape: (2, 4, 3)
size: 24


In [43]:
c = np.swapaxes(a,0,2)
print(c)
print('dimentions:',c.ndim)
print('shape:',c.shape)
print('size:',c.size)

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]
dimentions: 3
shape: (4, 3, 2)
size: 24


### ndarray.swapaxes()

In [3]:
# help(np.ndarray.swapaxes)
''' 
swapaxes(...)
    a.swapaxes(axis1, axis2)
    
    Return a view of the array with `axis1` and `axis2` interchanged.
    
    Refer to `numpy.swapaxes` for full documentation.
'''

' \nswapaxes(...)\n    a.swapaxes(axis1, axis2)\n    \n    Return a view of the array with `axis1` and `axis2` interchanged.\n    \n    Refer to `numpy.swapaxes` for full documentation.\n'

In [4]:
a = np.arange(24).reshape(2,3,4)
print(a) 
print('dimentions:',a.ndim)
print('shape:',a.shape)
print('size:',a.size)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
dimentions: 3
shape: (2, 3, 4)
size: 24


In [5]:
b = a.swapaxes(0,1)
print(b)
print('dimentions:',b.ndim)
print('shape:',b.shape)
print('size:',b.size)

[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]
dimentions: 3
shape: (3, 2, 4)
size: 24


# Joining Multiple Numpy Arrays into a Single One

## 1. concatenate()
- **dimentions must match**

In [3]:
# help(np.concatenate) 
''' 
concatenate(...)
    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
    
    Join a sequence of arrays along an existing axis.
'''

' \nconcatenate(...)\n    concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")\n    \n    Join a sequence of arrays along an existing axis.\n'

### Joining 2-D Arrays

#### -> Vertical Concatenation 
- **column size must match**

In [36]:
a = np.random.randint(1,101,(3,4))
print(a)
print('shape:',a.shape)

[[61 63 62 16]
 [92 51 33 51]
 [59 14 31 69]]
shape: (3, 4)


In [37]:
b = np.random.randint(1,101,(2,3))
print(b)
print('shape:',b.shape)

[[45 79  8]
 [36 71 91]]
shape: (2, 3)


In [13]:
c = np.concatenate((a,b))
print(c)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 3

In [38]:
d = np.random.randint(1,101,(2,4))
print(d)
print('shape:',d.shape)

[[12 59 22 32]
 [17 56 48 68]]
shape: (2, 4)


In [39]:
e = np.concatenate((a,d))  
print(e)
print('shape:',e.shape)

[[61 63 62 16]
 [92 51 33 51]
 [59 14 31 69]
 [12 59 22 32]
 [17 56 48 68]]
shape: (5, 4)


#### -> Horizontal Concatenation
- **row size must match**

In [41]:
a = np.random.randint(1,101,(3,4))
print(a)
print('shape:',a.shape)

[[13 61 58 65]
 [30 25 61 42]
 [30 56 54 76]]
shape: (3, 4)


In [42]:
b = np.random.randint(1,101,(2,4))
print(b)
print('shape:',b.shape)

[[ 9 64 62 40]
 [71 34 65 51]]
shape: (2, 4)


In [43]:
c = np.concatenate((a,b),axis=1) 
print(c)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 2

In [44]:
d = np.random.randint(1,101,(3,2))
print(d)
print('shape:',d.shape)

[[35 49]
 [93 16]
 [88  3]]
shape: (3, 2)


In [45]:
e = np.concatenate((a,d),axis=1)
print(e)
print('shape:',e.shape)

[[13 61 58 65 35 49]
 [30 25 61 42 93 16]
 [30 56 54 76 88  3]]
shape: (3, 6)


#### -> When V / H Concatenation is not possible

In [46]:
# Vertical Concatenation fails 
a = np.random.randint(1,101,(3,4))
print(a)
print('shape:',a.shape)

[[64 82 29 78]
 [80  1 64 29]
 [70 37 82 87]]
shape: (3, 4)


In [47]:
b = np.random.randint(1,101,(2,3))
print(b)
print('shape:',b.shape)

[[97 38 65]
 [93 37 56]]
shape: (2, 3)


In [48]:
c = np.concatenate((a,b),axis=None) 
print(c)
print('shape:',c.shape)

[64 82 29 78 80  1 64 29 70 37 82 87 97 38 65 93 37 56]
shape: (18,)


In [49]:
# Horizontal Concatenation fails 
a = np.random.randint(1,101,(3,4))
print(a)
print('shape:',a.shape)

[[78  8 59 99]
 [75  8 53 96]
 [43 78 61 60]]
shape: (3, 4)


In [50]:
b = np.random.randint(1,101,(2,4))
print(b)
print('shape:',b.shape)

[[34 59 94 15]
 [56 34 27 57]]
shape: (2, 4)


In [51]:
c = np.concatenate((a,b),axis=None)  
print(c)
print('shape:',c.shape)

[78  8 59 99 75  8 53 96 43 78 61 60 34 59 94 15 56 34 27 57]
shape: (20,)


#### -> When V/H Concatenation both are possible

In [32]:
# when both rowsizes and column suzes matche
a = np.arange(6).reshape(3,2)
b = np.arange(6).reshape(3,2)
c = np.concatenate((a,b),axis=0)
print(c)

[[0 1]
 [2 3]
 [4 5]
 [0 1]
 [2 3]
 [4 5]]


In [33]:
d = np.concatenate((a,b),axis=1)
print(d)

[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]]


In [34]:
e = np.concatenate((a,b),axis=None)
print(e)

[0 1 2 3 4 5 0 1 2 3 4 5]


### Joining 1-D Arrays

In [9]:
# Two 1-D Arrays
a = np.arange(4)
print('a:',a)
b = np.arange(5)
print('b:',b)
c = np.concatenate((a,b))
print('c:',c)
print('Dimentions:',c.ndim)

a: [0 1 2 3]
b: [0 1 2 3 4]
c: [0 1 2 3 0 1 2 3 4]
Dimentions: 1


In [13]:
# Three 1-D Arrays
d = np.concatenate((a,b,c))
print('d:',d)
print('Dimentions:',c.ndim)

d: [0 1 2 3 0 1 2 3 4 0 1 2 3 0 1 2 3 4]
Dimentions: 1


### Out Parameter and dtype

In [12]:
e = np.empty(18)
print(e)
np.concatenate((a,b,c),out=e)

[0.0e+000 4.9e-324 9.9e-324 1.5e-323 0.0e+000 4.9e-324 9.9e-324 1.5e-323
 2.0e-323 0.0e+000 4.9e-324 9.9e-324 1.5e-323 0.0e+000 4.9e-324 9.9e-324
 1.5e-323 2.0e-323]


array([0., 1., 2., 3., 0., 1., 2., 3., 4., 0., 1., 2., 3., 0., 1., 2., 3.,
       4.])

In [19]:
e = np.empty(18)
print(e)
np.concatenate((a,b,c),out=e,dtype='int')

[1.7192826e-316 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000 0.0000000e+000 0.0000000e+000
 0.0000000e+000 0.0000000e+000]


TypeError: concatenate() only takes `out` or `dtype` as an argument, but both were provided.

In [20]:
e = np.empty(18,dtype='int')
print(e)
np.concatenate((a,b,c),out=e)

[34798667        0        0        0        0        0        0        0
        0        0        0        0        0        0        0        0
        0        0]


array([0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 0, 1, 2, 3, 4])

In [21]:
print(e)

[0 1 2 3 0 1 2 3 4 0 1 2 3 0 1 2 3 4]


In [16]:
e = np.zeros(18,dtype=int)
print(e)
np.concatenate((a,b,c),out=e)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


array([0, 1, 2, 3, 0, 1, 2, 3, 4, 0, 1, 2, 3, 0, 1, 2, 3, 4])

In [17]:
print(e)

[0 1 2 3 0 1 2 3 4 0 1 2 3 0 1 2 3 4]


In [22]:
f = np.empty(12,dtype=int)
np.concatenate((a,b,c),out=f)

ValueError: Output array is the wrong shape

### dtype Parameter

In [24]:
a = np.arange(4)
print('a:',a)
b = np.arange(5)
print('b:',b)
c = np.concatenate((a,b),dtype=float)
print(c)

a: [0 1 2 3]
b: [0 1 2 3 4]
[0. 1. 2. 3. 0. 1. 2. 3. 4.]


In [25]:
d = np.concatenate((a,b),dtype=str)
print(d)

['0' '1' '2' '3' '0' '1' '2' '3' '4']


In [27]:
# cannot use out and dtype together
e = np.empty(9)
np.concatenate((a,b),out=e,dtype=int)

TypeError: concatenate() only takes `out` or `dtype` as an argument, but both were provided.

### Same Dimention

In [28]:
# Joinint 1-D and 2-D Arrays --> ValueError
a = np.arange(5)
b = np.arange(12).reshape(3,4)
c = np.concatenate((a,b))

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

### Joining 3-D Arrays

#### -> Same Size in Every Dimention

In [36]:
a = np.arange(8).reshape(2,2,2)
print(a)
b = np.arange(8).reshape(2,2,2)
print(b)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [37]:
# axis=0
c = np.concatenate((a,b))
print(c)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]

 [[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [38]:
# axis=1
d = np.concatenate((a,b),axis=1)
print(d)

[[[0 1]
  [2 3]
  [0 1]
  [2 3]]

 [[4 5]
  [6 7]
  [4 5]
  [6 7]]]


In [39]:
# axis=2
e = np.concatenate((a,b),axis=2)
print(e)

[[[0 1 0 1]
  [2 3 2 3]]

 [[4 5 4 5]
  [6 7 6 7]]]


In [40]:
# axis=None
f = np.concatenate((a,b),axis=None)
print(f)

[0 1 2 3 4 5 6 7 0 1 2 3 4 5 6 7]


#### -> Different Size in Every Dimention

In [41]:
a = np.arange(12).reshape(2,3,2)
print(a)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [42]:
b = np.arange(18).reshape(2,3,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [43]:
# axis=0
c = np.concatenate((a,b))
# axis 2 does not match

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 2 and the array at index 1 has size 3

In [44]:
d = np.concatenate((a,b),axis=1)
print(d)
# axis 2 does not match

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 2, the array at index 0 has size 2 and the array at index 1 has size 3

In [45]:
e = np.concatenate((a,b),axis=2)
print(e)

[[[ 0  1  0  1  2]
  [ 2  3  3  4  5]
  [ 4  5  6  7  8]]

 [[ 6  7  9 10 11]
  [ 8  9 12 13 14]
  [10 11 15 16 17]]]


## 2. stack()

In [50]:
# help(np.stack)
'''
stack(arrays, axis=0, out=None, *, dtype=None, casting='same_kind')
    Join a sequence of arrays along a new axis.

Returns
    -------
    stacked : ndarray
        The stacked array has one more dimension than the input arrays.
'''

"\nstack(arrays, axis=0, out=None, *, dtype=None, casting='same_kind')\n    Join a sequence of arrays along a new axis.\n\nReturns\n    -------\n    stacked : ndarray\n        The stacked array has one more dimension than the input arrays.\n"

### Stacking of 1-D Arrays

In [51]:
# Example 1
a = np.array([10,20,30])
b = np.array([40,50,60,70])
c = np.stack((a,b))

ValueError: all input arrays must have the same shape

#### axis=0 --> row-wise stacking

In [52]:
a = np.array([10,20,30])
b = np.array([40,50,60])
c = np.stack((a,b))
print(c)

[[10 20 30]
 [40 50 60]]


#### axis=1 --> column-wise stacking


In [53]:
a = np.array([10,20,30])
b = np.array([40,50,60])
c = np.stack((a,b),axis=1)
print(c)

[[10 40]
 [20 50]
 [30 60]]
