# Array Manipulation Functions

In [1]:
import numpy as np 

## 1. reshape() 
- **Condition:** Data should not change **==>** input size and output size must match
- **np.reshape()**  : Numpy Library Function
- **array.reshape()** : ndarray class method

#### 1A. 1-D Array

In [22]:
# creating 1-D array 
a = np.random.randint(1,101,10) 
print(a) 
print('Shape:',a.shape)
print('Size:',a.size)
# reshaping 1-D Array to 2-D Array 
b = np.reshape(a,(5,2))
print(b)

[15 58 58 72 30 31  1 72 91 24]
Shape: (10,)
Size: 10
[[15 58]
 [58 72]
 [30 31]
 [ 1 72]
 [91 24]]


In [5]:
help(np.reshape)

Help on _ArrayFunctionDispatcher in module numpy:

reshape(a, newshape, order='C')
    Gives a new shape to an array without changing its data.
    
    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped array using this index order.  'C'
        means to read / write the elements using C-like index order,
        with the last axis index changing fastest, back to the first
        axis index changing slowest. 'F' means to read / write the
        elements using Fortran-like index order, with the first index
 

#### 1B. 2-D Array

In [24]:
# creating 1-D Array 
a = np.random.randint(1,101,24)
print(a)
print('Shape:',a.shape)
print('Size:',a.size)
print('Dimentions:',a.ndim)

[ 96  50  66  74  48  27   5  85  31  50   4  37  48  44  39  27  55  42
  62  51   4   7 100  43]
Shape: (24,)
Size: 24
Dimentions: 1


In [25]:
# reshaping 1-D Array to 2-D Array
b = np.reshape(a,(3,8))
print(b)
print('Shape:',b.shape)
print('Size:',b.size)
print('Dimentions:',b.ndim)

[[ 96  50  66  74  48  27   5  85]
 [ 31  50   4  37  48  44  39  27]
 [ 55  42  62  51   4   7 100  43]]
Shape: (3, 8)
Size: 24
Dimentions: 2


In [26]:
# reshaping 2-D Array to 3-D Array
c = np.reshape(b,(2,3,4))
print(c)
print('Shape:',c.shape)
print('Size:',c.size)
print('Dimentions:',c.ndim)

[[[ 96  50  66  74]
  [ 48  27   5  85]
  [ 31  50   4  37]]

 [[ 48  44  39  27]
  [ 55  42  62  51]
  [  4   7 100  43]]]
Shape: (2, 3, 4)
Size: 24
Dimentions: 3


In [28]:
# reshaping 2-D Array to 4-D Array 
e = np.reshape(b,(2,2,2,3))
print(e) 
print('Shape:',e.shape)
print('Size',e.size)
print('Dimentions:',e.ndim)

[[[[ 96  50  66]
   [ 74  48  27]]

  [[  5  85  31]
   [ 50   4  37]]]


 [[[ 48  44  39]
   [ 27  55  42]]

  [[ 62  51   4]
   [  7 100  43]]]]
Shape: (2, 2, 2, 3)
Size 24
Dimentions: 4


In [27]:
# reshaping 2-D Array to 2-D Array of Different Shape 
d = np.reshape(b,(4,6))
print(d)
print('Shape:',d.shape)
print('Size',d.size)
print('Dimentions:',d.ndim)

[[ 96  50  66  74  48  27]
 [  5  85  31  50   4  37]
 [ 48  44  39  27  55  42]
 [ 62  51   4   7 100  43]]
Shape: (4, 6)
Size 24
Dimentions: 2


In [29]:
# reshaping 2-D Array to 2-D Array of Different Shape 
d = np.reshape(b,(6,4))
print(d)
print('Shape:',d.shape)
print('Size',d.size)
print('Dimentions:',d.ndim)

[[ 96  50  66  74]
 [ 48  27   5  85]
 [ 31  50   4  37]
 [ 48  44  39  27]
 [ 55  42  62  51]
 [  4   7 100  43]]
Shape: (6, 4)
Size 24
Dimentions: 2


In [30]:
# reshaping 2-D Array to 2-D Array of Different Shape 
d = np.reshape(b,(8,3))
print(d)
print('Shape:',d.shape)
print('Size',d.size)
print('Dimentions:',d.ndim)

[[ 96  50  66]
 [ 74  48  27]
 [  5  85  31]
 [ 50   4  37]
 [ 48  44  39]
 [ 27  55  42]
 [ 62  51   4]
 [  7 100  43]]
Shape: (8, 3)
Size 24
Dimentions: 2


#### 1C. View of Original only
- ***No New Object is Created***
- ***Change in One is reflected in the other***

In [32]:
a[0] = 7777
print(a)

[7777   50   66   74   48   27    5   85   31   50    4   37   48   44
   39   27   55   42   62   51    4    7  100   43]


In [33]:
print(b)

[[7777   50   66   74   48   27    5   85]
 [  31   50    4   37   48   44   39   27]
 [  55   42   62   51    4    7  100   43]]


In [34]:
print(c)

[[[7777   50   66   74]
  [  48   27    5   85]
  [  31   50    4   37]]

 [[  48   44   39   27]
  [  55   42   62   51]
  [   4    7  100   43]]]


In [35]:
print(d)

[[7777   50   66]
 [  74   48   27]
 [   5   85   31]
 [  50    4   37]
 [  48   44   39]
 [  27   55   42]
 [  62   51    4]
 [   7  100   43]]


In [36]:
print(e)

[[[[7777   50   66]
   [  74   48   27]]

  [[   5   85   31]
   [  50    4   37]]]


 [[[  48   44   39]
   [  27   55   42]]

  [[  62   51    4]
   [   7  100   43]]]]


In [38]:
b[2][0] = 9999
print(b)

[[7777   50   66   74   48   27    5   85]
 [  31   50    4   37   48   44   39   27]
 [9999   42   62   51    4    7  100   43]]


In [39]:
print(a)

[7777   50   66   74   48   27    5   85   31   50    4   37   48   44
   39   27 9999   42   62   51    4    7  100   43]


In [40]:
print(c)

[[[7777   50   66   74]
  [  48   27    5   85]
  [  31   50    4   37]]

 [[  48   44   39   27]
  [9999   42   62   51]
  [   4    7  100   43]]]


In [41]:
print(d)

[[7777   50   66]
 [  74   48   27]
 [   5   85   31]
 [  50    4   37]
 [  48   44   39]
 [  27 9999   42]
 [  62   51    4]
 [   7  100   43]]


In [42]:
print(e)

[[[[7777   50   66]
   [  74   48   27]]

  [[   5   85   31]
   [  50    4   37]]]


 [[[  48   44   39]
   [  27 9999   42]]

  [[  62   51    4]
   [   7  100   43]]]]


#### 1D. Taking Unknown Dimention Size as -1
- ***Value decided by Numpy automatically***
- ***Allowed Only Once***

In [52]:
a = np.random.randint(1,101,12)
print(a)
print('Shape',a.shape)

[18 32 69 13 18 97  9 22  1 48 19 83]
Shape (12,)


In [53]:
b = np.reshape(a,(6,-1))
print(b)
print('Shape',b.shape)

[[18 32]
 [69 13]
 [18 97]
 [ 9 22]
 [ 1 48]
 [19 83]]
Shape (12,)


In [54]:
b = np.reshape(a,(3,-1))
print(b)
print('Shape',b.shape)

[[18 32 69 13]
 [18 97  9 22]
 [ 1 48 19 83]]
Shape (3, 4)


In [55]:
b = np.reshape(a,(-1,6))
print(b)
print('Shape',b.shape)

[[18 32 69 13 18 97]
 [ 9 22  1 48 19 83]]
Shape (2, 6)


In [56]:
b = np.reshape(a,(-1,3))
print(b)
print('Shape',b.shape)

[[18 32 69]
 [13 18 97]
 [ 9 22  1]
 [48 19 83]]
Shape (4, 3)


In [58]:
c = np.reshape(a,(2,3,-1))
print(c)
print('Shape',c.shape)

[[[18 32]
  [69 13]
  [18 97]]

 [[ 9 22]
  [ 1 48]
  [19 83]]]
Shape (2, 3, 2)


In [59]:
c = np.reshape(a,(2,-1,3))
print(c)
print('Shape',c.shape)

[[[18 32 69]
  [13 18 97]]

 [[ 9 22  1]
  [48 19 83]]]
Shape (2, 2, 3)


In [61]:
c = np.reshape(a,(-1,2,2))
print(c)
print('Shape',c.shape)

[[[18 32]
  [69 13]]

 [[18 97]
  [ 9 22]]

 [[ 1 48]
  [19 83]]]
Shape (3, 2, 2)


#### 1E. ValueError : Different Cases

In [57]:
# b = np.reshape(a,(-1,-1))
# ValueError: can only specify one unknown dimension

In [63]:
# c = np.reshape(a,(5,-1))
# ValueError: cannot reshape array of size 12 into shape (5,newaxis)

#### 1F. order Argument (Optional)
- order='C' (Default): C Style : Row Major Order
- order='F' : Fortran Styly : Column Manor Order
- order='A' : Fortran Styly 

In [78]:
# Example 1 
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [80]:
# order='C'
b = np.reshape(a,(12,),'C')
print(b)
b = np.reshape(a,(12,))
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [81]:
# order='F'
c = np.reshape(a,(12,),'F')
print(c)

[ 0  4  8  1  5  9  2  6 10  3  7 11]


In [75]:
# Example 2
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [76]:
b = np.reshape(a,(6,4))
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [77]:
c = np.reshape(a,(6,4),'F')
print(c)

[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


## 2. resize()
- Input Size and Output Size need not match
- The Data may change
- We will get **Copy** , not view
- **np.resize()** : repeats elements of input array
- **array.resize()** : uses **zero** for **extra elements**, **Inline Modification**
- Taking Unknown Dimention Size as -1 is **not applicable**

In [100]:
# help(np.resize) 

In [83]:
a = np.arange(1,6)
print(a)

[1 2 3 4 5]


In [85]:
b = np.resize(a,(2,3))
print(b)

[[1 2 3]
 [4 5 1]]


#### 2A. np.resize()
**repeats elements of input array**

In [86]:
b = np.resize(a,(4,3))
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]]


#### 2B. Copy but not View
- **change in one does not affect the other**

In [89]:
a[0] = 7777
print(a)

[7777    2    3    4    5]


In [90]:
print(b)

[[1 2 3]
 [4 5 1]
 [2 3 4]
 [5 1 2]]


#### 2C. Taking Unknown Dimention Size as -1 
***not applicable***

In [93]:
# b = np.resize(a,(5,-1))
# ValueError: all elements of `new_shape` must be non-negative

#### 2D. array.resize()
- uses **zero** for extra elements
- **Inline Modification**

In [94]:
b = a.resize(5,3)

ValueError: cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False

In [98]:
a = np.arange(1,6)
print(a)
b = a.resize(5,3)
print(a)
# inline modification check 
print(b)

[1 2 3 4 5]
[[1 2 3]
 [4 5 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
None
