In [1]:
import numpy as np

# 1. split()

In [3]:
# help(np.split)

## A. Section Based

### 1-D Arrays

In [4]:
a = np.arange(1,10)
print(a)

[1 2 3 4 5 6 7 8 9]


In [11]:
sub_arrays = np.split(a,3)
print(sub_arrays)

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [12]:
for arr in sub_arrays:
    print(arr)

[1 2 3]
[4 5 6]
[7 8 9]


In [13]:
for arr in sub_arrays:
    for elements in arr:
        print(elements)

1
2
3
4
5
6
7
8
9


In [14]:
print(sub_arrays[0])

[1 2 3]


In [15]:
new_sub_arrays = np.split(a,4)
# no. of sections should be of eqal size 

ValueError: array split does not result in an equal division

### 2-D Arrays

#### Vertical Split --> row-wise --> axis=0

In [16]:
a = np.arange(1,25).reshape(6,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [18]:
split_arrays = np.split(a,2)
print(split_arrays[0])
print()
print(split_arrays[1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]


In [19]:
split_arrays = np.split(a,3)
print(split_arrays[0])
print()
print(split_arrays[1])
print()
print(split_arrays[2])

[[1 2 3 4]
 [5 6 7 8]]

[[ 9 10 11 12]
 [13 14 15 16]]

[[17 18 19 20]
 [21 22 23 24]]


In [20]:
split_arrays = np.split(a,6)
for arr in split_arrays:
    print(arr)


[[1 2 3 4]]
[[5 6 7 8]]
[[ 9 10 11 12]]
[[13 14 15 16]]
[[17 18 19 20]]
[[21 22 23 24]]


In [21]:
split_arrays = np.split(a,4)

ValueError: array split does not result in an equal division

#### Horizontal Split --> column-wise --> axis=1

In [22]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [24]:
split_arrays = np.split(a,2,axis=1)
print(split_arrays)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12],
       [15, 16],
       [19, 20],
       [23, 24]])]


In [25]:
print(split_arrays[0])
print()
print(split_arrays[1])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]
 [21 22]]

[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]
 [19 20]
 [23 24]]


In [26]:
split_arrays = np.split(a,4,axis=1)
for arr in split_arrays:
    print(arr)
    print()

[[ 1]
 [ 5]
 [ 9]
 [13]
 [17]
 [21]]

[[ 2]
 [ 6]
 [10]
 [14]
 [18]
 [22]]

[[ 3]
 [ 7]
 [11]
 [15]
 [19]
 [23]]

[[ 4]
 [ 8]
 [12]
 [16]
 [20]
 [24]]



## B. Index Based

### 1-D Arrays

In [28]:
a = np.arange(10,101,10)
print(a)

[ 10  20  30  40  50  60  70  80  90 100]


In [33]:
# Example 1
split_arrays = np.split(a,[3,7])
print(split_arrays)
for arr in split_arrays:
    print(arr)

[array([10, 20, 30]), array([40, 50, 60, 70]), array([ 80,  90, 100])]
[10 20 30]
[40 50 60 70]
[ 80  90 100]


In [35]:
# Example 2
split_arrays = np.split(a,[2,5,7])
print(split_arrays)
for arr in split_arrays:
    print(arr)

[array([10, 20]), array([30, 40, 50]), array([60, 70]), array([ 80,  90, 100])]
[10 20]
[30 40 50]
[60 70]
[ 80  90 100]


### 2-D Arrays

#### Vertical Split --> row-wise --> axis=0

In [36]:
a = np.arange(1,13).reshape(6,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [37]:
# Example 1
split_arrays = np.split(a,[3,4])
print(split_arrays)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [38]:
for arr in split_arrays:
    print(arr)
    print()

[[1 2]
 [3 4]
 [5 6]]

[[7 8]]

[[ 9 10]
 [11 12]]



In [39]:
# Example 2
split_arrays = np.split(a,[1,3,4])
print(split_arrays)

[array([[1, 2]]), array([[3, 4],
       [5, 6]]), array([[7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [40]:
for arr in split_arrays:
    print(arr)
    print()

[[1 2]]

[[3 4]
 [5 6]]

[[7 8]]

[[ 9 10]
 [11 12]]



#### Horizontal Split --> Column-wise --> axis=1

In [42]:
a = np.arange(1,19).reshape(3,6)
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]


In [43]:
# Example 1
split_arrays = np.split(a,[1,3,5],axis=1)
print(split_arrays)

[array([[ 1],
       [ 7],
       [13]]), array([[ 2,  3],
       [ 8,  9],
       [14, 15]]), array([[ 4,  5],
       [10, 11],
       [16, 17]]), array([[ 6],
       [12],
       [18]])]


In [44]:
for arr in split_arrays:
    print(arr)
    print()

[[ 1]
 [ 7]
 [13]]

[[ 2  3]
 [ 8  9]
 [14 15]]

[[ 4  5]
 [10 11]
 [16 17]]

[[ 6]
 [12]
 [18]]



In [45]:
# Example 2 *not usual 
split_arrays = np.split(a,[2,4,4],axis=1)
print(split_arrays)

[array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4],
       [ 9, 10],
       [15, 16]]), array([], shape=(3, 0), dtype=int64), array([[ 5,  6],
       [11, 12],
       [17, 18]])]


In [46]:
for arr in split_arrays:
    print(arr)
    print()

[[ 1  2]
 [ 7  8]
 [13 14]]

[[ 3  4]
 [ 9 10]
 [15 16]]

[]

[[ 5  6]
 [11 12]
 [17 18]]



In [47]:
# Example 3 *not usual 
split_arrays = np.split(a,[0,2,6],axis=1)
print(split_arrays)

[array([], shape=(3, 0), dtype=int64), array([[ 1,  2],
       [ 7,  8],
       [13, 14]]), array([[ 3,  4,  5,  6],
       [ 9, 10, 11, 12],
       [15, 16, 17, 18]]), array([], shape=(3, 0), dtype=int64)]


In [48]:
for arr in split_arrays:
    print(arr)
    print()

[]

[[ 1  2]
 [ 7  8]
 [13 14]]

[[ 3  4  5  6]
 [ 9 10 11 12]
 [15 16 17 18]]

[]



In [49]:
# Example 4 *not usual 
split_arrays = np.split(a,[0,3,8],axis=1)
print(split_arrays)

[array([], shape=(3, 0), dtype=int64), array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15]]), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]]), array([], shape=(3, 0), dtype=int64)]


In [50]:
for arr in split_arrays:
    print(arr)
    print()

[]

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]]

[[ 4  5  6]
 [10 11 12]
 [16 17 18]]

[]



In [51]:
# Example 5 *not usual **Dangerous Combinations
split_arrays = np.split(a,[1,5,3],axis=1)
print(split_arrays)

[array([[ 1],
       [ 7],
       [13]]), array([[ 2,  3,  4,  5],
       [ 8,  9, 10, 11],
       [14, 15, 16, 17]]), array([], shape=(3, 0), dtype=int64), array([[ 4,  5,  6],
       [10, 11, 12],
       [16, 17, 18]])]


In [52]:
for arr in split_arrays:
    print(arr)
    print()

[[ 1]
 [ 7]
 [13]]

[[ 2  3  4  5]
 [ 8  9 10 11]
 [14 15 16 17]]

[]

[[ 4  5  6]
 [10 11 12]
 [16 17 18]]



# 2. vsplit()
- vsplit() ==> Vertical Split ==> row-wise

## A. Section Based

### 1-D Arrays --> not possible

In [53]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [54]:
split_arrays = np.vsplit(a,2)

ValueError: vsplit only works on arrays of 2 or more dimensions

### 2-D Arrays

In [55]:
a = np.arange(1,13).reshape(6,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [56]:
# Example 1
split_arrays = np.vsplit(a,2)
print(split_arrays)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]


In [57]:
for arr in split_arrays:
    print(arr)
    print()

[[1 2]
 [3 4]
 [5 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]



In [58]:
# Example 2
split_arrays = np.vsplit(a,3)
print(split_arrays)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [59]:
for arr in split_arrays:
    print(arr)
    print()

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]

[[ 9 10]
 [11 12]]



In [62]:
# Example 3
split_arrays = np.vsplit(a,6)
print(split_arrays)

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [63]:
for arr in split_arrays:
    print(arr)
    print()

[[1 2]]

[[3 4]]

[[5 6]]

[[7 8]]

[[ 9 10]]

[[11 12]]



## B. Index Based

### 2-D Arrays

In [64]:
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [65]:
split_arrays = np.split(a,[1,4])
print(split_arrays)

[array([[1, 2]]), array([[3, 4],
       [5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [66]:
for arr in split_arrays:
    print(arr)
    print()

[[1 2]]

[[3 4]
 [5 6]
 [7 8]]

[[ 9 10]
 [11 12]]



# 3. hsplit()
- hsplit() ==> Horizontal Split ==> column-wise

## A. Section Based

### 1-D Arrays

In [67]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
split_arrays = np.hsplit(a,2)
print(split_arrays)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]


In [69]:
for arr in split_arrays:
    print(arr)
    print()

[0 1 2 3 4]

[5 6 7 8 9]



In [70]:
split_arrays = np.hsplit(a,10)
print(split_arrays)

[array([0]), array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([7]), array([8]), array([9])]


In [71]:
for arr in split_arrays:
    print(arr)
    print()

[0]

[1]

[2]

[3]

[4]

[5]

[6]

[7]

[8]

[9]



In [72]:
split_arrays = np.hsplit(a,4)

ValueError: array split does not result in an equal division

### 2-D Arrays

In [74]:
a = np.arange(1,13).reshape(3,4)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [75]:
# Example 1
split_arrays = np.hsplit(a,2)
print(split_arrays)

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [76]:
for arr in split_arrays:
    print(arr)
    print()

[[ 1  2]
 [ 5  6]
 [ 9 10]]

[[ 3  4]
 [ 7  8]
 [11 12]]



In [79]:
# Example 2
split_arrays = np.hsplit(a,4)
print(split_arrays)

[array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]


In [80]:
for arr in split_arrays:
    print(arr)
    print()

[[1]
 [5]
 [9]]

[[ 2]
 [ 6]
 [10]]

[[ 3]
 [ 7]
 [11]]

[[ 4]
 [ 8]
 [12]]



In [81]:
# Example 3
split_arrays = np.hsplit(a,3)
print(split_arrays)

ValueError: array split does not result in an equal division

## B. Index Based

#### 1-D Arrays

In [82]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [87]:
split_arrays = np.hsplit(a,[2,4,7])
print(split_arrays)

[array([0, 1]), array([2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [88]:
for arr in split_arrays:
    print(arr)
    print()

[0 1]

[2 3]

[4 5 6]

[7 8 9]



### 2-D Arrays

In [89]:
a = np.arange(24).reshape(4,6)
print(a)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [90]:
# Example 1
split_arrays = np.hsplit(a,[2,5])
print(split_arrays)

[array([[ 0,  1],
       [ 6,  7],
       [12, 13],
       [18, 19]]), array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16],
       [20, 21, 22]]), array([[ 5],
       [11],
       [17],
       [23]])]


In [91]:
for arr in split_arrays:
    print(arr)
    print()

[[ 0  1]
 [ 6  7]
 [12 13]
 [18 19]]

[[ 2  3  4]
 [ 8  9 10]
 [14 15 16]
 [20 21 22]]

[[ 5]
 [11]
 [17]
 [23]]



In [92]:
# Example 2
split_arrays = np.hsplit(a,[1,4])
print(split_arrays)

[array([[ 0],
       [ 6],
       [12],
       [18]]), array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]]), array([[ 4,  5],
       [10, 11],
       [16, 17],
       [22, 23]])]


In [93]:
for arr in split_arrays:
    print(arr)
    print()

[[ 0]
 [ 6]
 [12]
 [18]]

[[ 1  2  3]
 [ 7  8  9]
 [13 14 15]
 [19 20 21]]

[[ 4  5]
 [10 11]
 [16 17]
 [22 23]]



# 4. dsplit()
- min. 3-D array
- split based on axis=2 ==> column-wise

In [4]:
# help(np.dsplit)

## A. Section Based

### 3-D Array

In [5]:
a = np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [7]:
split_arrays = np.dsplit(a,2)
print(split_arrays)

[array([[[ 0,  1],
        [ 4,  5],
        [ 8,  9]],

       [[12, 13],
        [16, 17],
        [20, 21]]]), array([[[ 2,  3],
        [ 6,  7],
        [10, 11]],

       [[14, 15],
        [18, 19],
        [22, 23]]])]


In [8]:
for arr in split_arrays:
    print(arr)
    print()

[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[12 13]
  [16 17]
  [20 21]]]

[[[ 2  3]
  [ 6  7]
  [10 11]]

 [[14 15]
  [18 19]
  [22 23]]]



## B. Index Based

### 3-D Array

In [9]:
a = np.arange(24).reshape(2,3,4)
print(a)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [10]:
split_arrays = np.dsplit(a,[1,3])
print(split_arrays)

[array([[[ 0],
        [ 4],
        [ 8]],

       [[12],
        [16],
        [20]]]), array([[[ 1,  2],
        [ 5,  6],
        [ 9, 10]],

       [[13, 14],
        [17, 18],
        [21, 22]]]), array([[[ 3],
        [ 7],
        [11]],

       [[15],
        [19],
        [23]]])]


In [13]:
for arr in split_arrays:
    print(arr)
    print()

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]

[[[ 1  2]
  [ 5  6]
  [ 9 10]]

 [[13 14]
  [17 18]
  [21 22]]]

[[[ 3]
  [ 7]
  [11]]

 [[15]
  [19]
  [23]]]



# 5. array_split()

In [14]:
help(np.array_split)

Help on _ArrayFunctionDispatcher in module numpy:

array_split(ary, indices_or_sections, axis=0)
    Split an array into multiple sub-arrays.
    
    Please refer to the ``split`` documentation.  The only difference
    between these functions is that ``array_split`` allows
    `indices_or_sections` to be an integer that does *not* equally
    divide the axis. For an array of length l that should be split
    into n sections, it returns l % n sub-arrays of size l//n + 1
    and the rest of size l//n.
    
    See Also
    --------
    split : Split array into multiple sub-arrays of equal size.
    
    Examples
    --------
    >>> x = np.arange(8.0)
    >>> np.array_split(x, 3)
    [array([0.,  1.,  2.]), array([3.,  4.,  5.]), array([6.,  7.])]
    
    >>> x = np.arange(9)
    >>> np.array_split(x, 4)
    [array([0, 1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]



## A. Section Based

### 1-D Array

In [15]:
a = np.arange(11)
split_arrays = np.array_split(a,3)
print(split_arrays)
print()
for arr in split_arrays:
    print(arr)
    print()

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10])]

[0 1 2 3]

[4 5 6 7]

[ 8  9 10]



### 2-D Array

#### Vertical Split

In [16]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [17]:
split_arrays = np.array_split(a,2)
for arr in split_arrays:
    print(arr)
    print()

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]]



#### Horizontal Split

In [18]:
a = np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [19]:
split_arrays = np.array_split(a,3,axis=1)
for arr in split_arrays:
    print(arr)
    print()

[[0 1]
 [4 5]
 [8 9]]

[[ 2]
 [ 6]
 [10]]

[[ 3]
 [ 7]
 [11]]



## B. Index Based --> Exactly Same as split()

### 1-D Array

In [20]:
a = np.arange(11)
split_arrays = np.array_split(a,[2,5,7])
print(split_arrays)
print()
for arr in split_arrays:
    print(arr)
    print()



[array([0, 1]), array([2, 3, 4]), array([5, 6]), array([ 7,  8,  9, 10])]

[0 1]

[2 3 4]

[5 6]

[ 7  8  9 10]

