## Creating Numpy Arrays

#### 1. array()

In [41]:
# 1-D Array using List
import numpy as np
L = [10,20,30]
a = np.array(L)
print(L)
print(type(L))
print(a)
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.shape)      # (3,) --> (size of array , )
print(a.size)
# a1 = np.array(L,str)
# print(a1.dtype)

[10, 20, 30]
<class 'list'>
[10 20 30]
<class 'numpy.ndarray'>
1
int64
(3,)
3


In [11]:
# import numpy as np
# help(np.array)
# array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,like=None)

In [42]:
# 2-D Array
L = [[10,20,30],[40,50,60],[70,80,90]]
a = np.array(L)
print(type(a))
print(a.ndim)
print(a)
print(a.shape)
print(a.size)

<class 'numpy.ndarray'>
2
[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
9


In [43]:
# 1-D Array using Tuple
t = ('shubham','kumar','gupta')
a = np.array(t)
print(a)
print(type(a))
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)        # <U7 --> string

['shubham' 'kumar' 'gupta']
<class 'numpy.ndarray'>
1
(3,)
3
<U7


In [44]:
# Homo Elements --> upcasting
L = [7,'Dhoni',10,'Sachin',18,'Kohli',45,'Rohit']
a = np.array(L)
print(L)
print(a)
print(a.dtype)
L1 = [10,20,30.5]
a1 = np.array(L1)
print(a1)
print(a1.dtype)

[7, 'Dhoni', 10, 'Sachin', 18, 'Kohli', 45, 'Rohit']
['7' 'Dhoni' '10' 'Sachin' '18' 'Kohli' '45' 'Rohit']
<U21
[10.  20.  30.5]
float64


In [51]:
# How to create an array of a particular type
L1 = [10,20,30.5,0]
a1 = np.array(L1,int)
print(a1)
a2 = np.array(L1,bool)
print(a2)
a3 = np.array(L1,str)
print(a3)
L2 = [7,'Dhoni',10,'Sachin',18,'Kohli',45,'Rohit']
# a = np.array(L2,int)       # ValueError

[10 20 30  0]
[ True  True  True False]
['10' '20' '30.5' '0']


In [57]:
# object type array --> Array with Heterogeneous Elements 
L = [7,'Dhoni',10,'Sachin',18,'Kohli',45,'Rohit',True,10.5,10+20j]
a = np.array(L,object)
print(a)
print(a.dtype)
a1 = np.array(L)
print(a1)
print(a1.dtype)

[7 'Dhoni' 10 'Sachin' 18 'Kohli' 45 'Rohit' True 10.5 (10+20j)]
object
['7' 'Dhoni' '10' 'Sachin' '18' 'Kohli' '45' 'Rohit' 'True' '10.5'
 '(10+20j)']
<U64
