In [2]:
import numpy as np

In [8]:
# array()
L = [10,20,30]
a = np.array(L,float)
print(a)
print(a.ndim)
print(a.dtype)
print(a.shape)
print(a.size)

[10. 20. 30.]
1
float64
(3,)
3


In [26]:
# arange()
a = np.arange(10,21,2,float)
# dtype=str --> TypeError
# dtype=bool --> TypeError
print(a)

[10. 12. 14. 16. 18. 20.]


In [31]:
# Alternative of arange() --> array() is a better alternative of arange()
a = np.array(range(0,21,2),str)
print(a)
print(a.dtype)
a = np.array(range(0,21,2),bool)
print(a)
print(a.dtype)
a = np.array(range(0,21,2),float)
print(a)
print(a.dtype)
a = np.array(range(0,21,2))
print(a)
print(a.dtype)

['0' '2' '4' '6' '8' '10' '12' '14' '16' '18' '20']
<U2
[False  True  True  True  True  True  True  True  True  True  True]
bool
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]
float64
[ 0  2  4  6  8 10 12 14 16 18 20]
int64


In [52]:
# linspace() --> linspace is like an advancement to arange()
a = np.linspace(50,10,5)    # evenly spaced values in descending order
print(a)
a = np.linspace(50,10,5,dtype=int)
print(a)
a = np.linspace(50,10,5,dtype=str)
print(a)
a = np.linspace(50,10,5,dtype=bool)
print(a)

[50. 40. 30. 20. 10.]
[50 40 30 20 10]
['50.0' '40.0' '30.0' '20.0' '10.0']
[ True  True  True  True  True]


In [62]:
# zeros() --> the biggest advantage of using zeros(),ones() or full() is that we can create multi-dimentional arrays
shape_of_array = (2,3)
a = np.zeros(shape_of_array,dtype=int)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)

[[0 0 0]
 [0 0 0]]
int64
2
(2, 3)
6


In [63]:
shape_of_array = (2,3)
a = np.zeros(shape_of_array,dtype=str)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)

[['' '' '']
 ['' '' '']]
<U1
2
(2, 3)
6


In [66]:
shape_of_array = (2,3)
a = np.zeros(shape_of_array,dtype=bool)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)

[[False False False]
 [False False False]]
bool
2
(2, 3)
6


In [64]:
shape_of_array = (2,3,4)
a = np.zeros(shape_of_array)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
float64
3
(2, 3, 4)
24


In [65]:
shape_of_array = (2,3,4,5)
a = np.zeros(shape_of_array)
print(a)
print(a.dtype)
print(a.ndim)
print(a.shape)
print(a.size)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]
float64
4
(2, 3, 4, 5)
120


In [71]:
# ones()
shape_of_array = (2,3)
a = np.ones(shape_of_array)
print(a)
print()
shape_of_array = (2,3)
a = np.ones(shape_of_array,dtype=int)
print(a)
print()
shape_of_array = (2,3)
a = np.ones(shape_of_array,dtype=str)
print(a)
print()

[[1. 1. 1.]
 [1. 1. 1.]]

[[1 1 1]
 [1 1 1]]

[['1' '1' '1']
 ['1' '1' '1']]


In [74]:
# full()
shape_of_array = (2,3)
a = np.full(shape_of_array,7)
print(a)

[[7 7 7]
 [7 7 7]]


In [75]:
shape_of_array = (2,3)
a = np.full(shape_of_array,7,str)
print(a)

[['7' '7' '7']
 ['7' '7' '7']]


In [8]:
a = np.eye(3,4,1,int)
print(a)

[[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [6]:
a = np.identity(5,int)
print(a)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [10]:
# creating an array with Heterogeneous Daya Types --> I love this hack !
L = (7,'dhoni',True,7.77,10+20j)
print(L)
a = np.array(L,dtype=object)
print(a)
print(a.dtype)

(7, 'dhoni', True, 7.77, (10+20j))
[7 'dhoni' True 7.77 (10+20j)]
object
